##
# Server
##
server:
    port: 8080
    servlet:
        context-path: /
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include-exception: false

##
# Spring Application
##
spring:
    application:
        name: ingressos
    output:
        ansi:
            enabled: ALWAYS